### ISSUE TITLE
Bullets are bunching up

### ISSUE THREAD

**Issue by tboho1** [playmint/playerchain-demo#149]
Bullets behave strangely, often appearing to lag behind the ship or bunching up into clusters. They need to be a consistent speed plus the ship's speed.

**Comment by PlaymintPaul** [comment]
I'm not sure why this happens. The code has them always moving at the same speed so not sure why they are bunching...

**Comment by chrisfarms** [comment]
the bunching is because the cap on bullet velocity is less than the max velocity of the ship + bullet velocity

(ie when you are flying in the direction of bullet fire they will be closer together than if you were flying backwards)

I have raised the cap in #167 which resolves this issue and things look better ... but of course now bullets can go faster ... after new collision stuff gets in we will need some number noodling again
